### ISSUE TITLE
[default] connection not recognized

### ISSUE THREAD

**Issue by toabctl** [williamh/pybugz#36]
my ~/.bugzrc file is:

[gnome]
base: https://bugzilla.gnome.org/xmlrpc.cgi
user: XXXXXXX
password: XXXXX
encoding: utf-8

[default]
connection: gnome

but when i search for a bug with "bugz search network" i get bugs from gentoo. seems that the default connection is not recognized.

**Comment by clrh** [comment]
I don't know if it can helped but I got a similar error with 0.10.1

$ bugz --version
bugz 0.10.1
$ bugz -b http://xxx --skip-auth get -a -n xxxx
 * Using http://xxx
 * Getting bug 13771 ..
Traceback (most recent call last):
  File "/usr/bin/bugz", line 67, in <module>
    main()
  File "/usr/bin/bugz", line 42, in main
    args.func(bugz, args)
  File "/usr/lib/python2.7/dist-packages/bugz/cli.py", line 270, in get
    result = self.bzcall(self.bz.Bug.get, {'ids':[args.bugid]})
  File "/usr/lib/python2.7/dist-packages/bugz/cli.py", line 177, in bzcall
    return method(*args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/dist-packages/bugz/bugzilla.py", line 56, in request
    return self.parse_response(resp)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1467, in parse_response
    p.feed(data)
  File "/usr/lib/python2.7/xmlrpclib.py", line 557, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: mismatched tag: line 98, column 4

**Comment by part1zano** [comment]
[1:03:49] 0 [che@thinkpad ~]% bugz search pygitup
ssl ok
 * Using http://bugs.freebsd.org/bugzilla 
 * Searching for 'pygitup' 
Traceback (most recent call last):
  File "/usr/local/bin/bugz", line 67, in <module>
    main()
  File "/usr/local/bin/bugz", line 42, in main
    args.func(bugz, args)
  File "/usr/local/lib/python2.7/site-packages/bugz/cli.py", line 283, in search
    result = self.bzcall(self.bz.Bug.search, params)['bugs']
  File "/usr/local/lib/python2.7/site-packages/bugz/cli.py", line 189, in bzcall
    return method(*self.set_token(*args))
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python2.7/site-packages/bugz/bugzilla.py", line 62, in request
    return self.parse_response(resp)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 1476, in parse_response
    p.feed(data)
  File "/usr/local/lib/python2.7/xmlrpclib.py", line 558, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: mismatched tag: line 93, column 4
[1:04:55] 1 [che@thinkpad ~]% bugz --version
ssl ok
bugz 0.10.1

**Comment by kulinshah** [comment]
Hi @clrh ,
I am getting the same error with 0.10.1.
How did you fix it?
