### ISSUE TITLE
pybugz does not verify the bugzilla server certificate

### ISSUE THREAD

**Issue by asarubbo** [williamh/pybugz#44]
pybugz should verify the certificate when it uses an SSL connection.

**Comment by asarubbo** [comment]
Hello

To be honest, I really did not remember that I opened this bug.

Anyway, now I have The opposite problem.
I have a bugzilla in my lan under https and when I try to connect to it I get:
```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.4/bugz", line 9, in <module>
    load_entry_point('pybugz==0.12.1', 'console_scripts', 'bugz')()
  File "/usr/lib64/python3.4/site-packages/bugz/cli.py", line 702, in main
    args.func(settings)
  File "/usr/lib64/python3.4/site-packages/bugz/cli.py", line 640, in post
    result = settings.call_bz(settings.bz.Bug.create, params)
  File "/usr/lib64/python3.4/site-packages/bugz/settings.py", line 138, in call_bz
    return method(params)
  File "/usr/lib64/python3.4/xmlrpc/client.py", line 1098, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python3.4/xmlrpc/client.py", line 1437, in __request
    verbose=self.__verbose
  File "/usr/lib64/python3.4/xmlrpc/client.py", line 1140, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.4/xmlrpc/client.py", line 1152, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib64/python3.4/xmlrpc/client.py", line 1264, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib64/python3.4/xmlrpc/client.py", line 1294, in send_content
    connection.endheaders(request_body)
  File "/usr/lib64/python3.4/http/client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.4/http/client.py", line 922, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.4/http/client.py", line 857, in send
    self.connect()
  File "/usr/lib64/python3.4/http/client.py", line 1231, in connect
    server_hostname=server_hostname)
  File "/usr/lib64/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/usr/lib64/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/usr/lib64/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

So bugz should have something to skip the certificate validation.

**Comment by asarubbo** [comment]
This patch from @floppym works for me against the current git master:
https://gist.github.com/anonymous/e84158a9eec851c8f017a1127086cd80

But it should work only if the user passes something like "--skip-ssl-verification"

**Comment by williamh** [comment]
@asarubbo Please test against master now with the --insecure  option and let me know if it works.

**Comment by asarubbo** [comment]
yes, it works for me
