### ISSUE TITLE
Traceback while doing search...

### ISSUE THREAD

**Issue by aniruddha-a** [williamh/pybugz#64]
Issue with latest snapshot (head at 128ac8d724d7994477702a4b7455e207bf6b4d37)

I have `bugzilla 4.4.4` and `Python 3.3.0`,  today morning I installed latest `PyBugz` current snapshot
and I see the following error:

```
$ bugz --connection myconn --debug  3 search --assigned-to me@mycompany.com
 * Using http://bugzilla.mycompany.com 
 * Searching for bugs with the following options:
 *    assigned_to          = me@mycompany.com
Traceback (most recent call last):
  File "/usr/local/bin/bugz", line 72, in <module>
    sys.exit(main())
  File "/usr/local/bin/bugz", line 47, in main
    args.func(bugz, args)
  File "/usr/local/lib/python3.3/site-packages/bugz/cli.py", line 263, in search
    result = self.call_bz(self.bz.Bug.search, params)['bugs']
  File "/usr/local/lib/python3.3/site-packages/bugz/cli.py", line 162, in call_bz
    return method(*self.set_token(*args))
  File "/usr/local/lib/python3.3/xmlrpc/client.py", line 1090, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/lib/python3.3/xmlrpc/client.py", line 1419, in __request
    verbose=self.__verbose
  File "/usr/local/lib/python3.3/site-packages/bugz/bugzilla.py", line 55, in request
    return self.parse_response(resp)
  File "/usr/local/lib/python3.3/xmlrpc/client.py", line 1312, in parse_response
    p.feed(data)
  File "/usr/local/lib/python3.3/xmlrpc/client.py", line 446, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: mismatched tag: line 116, column 4
```

**Comment by aniruddha-a** [comment]
I moved to Ubuntu 16.06 (Xenial) and just gave this a try, the issue still persists :(

```
$ python3 --version
Python 3.5.2
$ /usr/local/bin/bugz --version
bugz 0.13

```
