### ISSUE TITLE
xmlrpc.client is invalid import in Python 3.4 

### ISSUE THREAD

**Issue by kaushikvelusamy** [williamh/pybugz#80]
```
kaushik@kaushik-virtual-machine:~/pybugz$ bugz
Traceback (most recent call last):
  File "/usr/local/bin/bugz", line 23, in <module>
    from bugz.argparser import make_arg_parser
  File "/usr/local/lib/python3.4/dist-packages/bugz/argparser.py", line 3, in <module>
    import bugz.cli
  File "/usr/local/lib/python3.4/dist-packages/bugz/cli.py", line 7, in <module>
    import xmlrpc.client
ImportError: No module named 'xmlrpc.client'
```

**Comment by vapier** [comment]
this bug is invalid.  "import xmlrpc.client" is valid python, but your system doesn't have it installed.  you need to install it on your system.
