### ISSUE TITLE
drop support for tokens (was Login issue with tokens - socket.gaierror: [Errno -2] Name or service not known)

### ISSUE THREAD

**Issue by kaushikvelusamy** [williamh/pybugz#81]
Couldnt login to bugzilla with the following details
socket.gaierror: [Errno -2] Name or service not known
kaushik@kaushik-virtual-machine:~/pybugz$ source ~/.bashrc
kaushik@kaushik-virtual-machine:~/pybugz$ vi ~/.bugzrc
kaushik@kaushik-virtual-machine:~/pybugz$ vi ~/.bashrc
kaushik@kaushik-virtual-machine:~/pybugz$ source ~/.bashrc
kaushik@kaushik-virtual-machine:~/pybugz$ bugz --connection mozilla login
 * Info: Using [mozilla] (https://bugzilla.mozilla.com/xmlrpc.cgi)
 * Info: Logging in
Traceback (most recent call last):
  File "/usr/local/bin/bugz", line 58, in <module>
    sys.exit(main())
  File "/usr/local/bin/bugz", line 43, in main
    args.func(conn)
  File "/usr/local/lib/python3.3/dist-packages/bugz/cli.py", line 374, in login
    result = conn.call_bz(conn.bz.User.login, params)
  File "/usr/local/lib/python3.3/dist-packages/bugz/connection.py", line 154, in call_bz
    return method(params)
  File "/usr/lib/python3.3/xmlrpc/client.py", line 1090, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.3/xmlrpc/client.py", line 1419, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.3/xmlrpc/client.py", line 1132, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.3/xmlrpc/client.py", line 1143, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.3/xmlrpc/client.py", line 1255, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.3/xmlrpc/client.py", line 1285, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.3/http/client.py", line 1061, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.3/http/client.py", line 906, in _send_output
    self.send(msg)
  File "/usr/lib/python3.3/http/client.py", line 844, in send
    self.connect()
  File "/usr/lib/python3.3/http/client.py", line 1198, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.3/socket.py", line 417, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known
kaushik@kaushik-virtual-machine:~/pybugz$ vi bu
bugz/  build/
kaushik@kaushik-virtual-machine:~/pybugz$ vi ~/.bugz_tokens
kaushik@kaushik-virtual-machine:~/pybugz$ cat ~/.bugz_tokens
[Mozilla]
token = 531271-62L1L3lflf

kaushik@kaushik-virtual-machine:~/pybugz$ cat ~/.bugzrc
[mozilla]
base = https://bugzilla.mozilla.com/xmlrpc.cgi
user = XXXXXXXX@gmail.com
password = XXXXXXXX
kaushik@kaushik-virtual-machine:~/pybugz$

**Comment by williamh** [comment]
It looks like we should not support tokens.
In the latest bugzilla documentation, upstream recommends against using them and they are going to be dropped completely in the future [1].

[1] https://www.bugzilla.org/docs/5.0/en/html/api/Bugzilla/WebService.html
